### ISSUE TITLE
[docs] WebOS dev account creation link is unreachable

### ISSUE THREAD

**Issue by mikegsrv** [yandex/rtv#11]
Hello! 
Seems like the link to the WebOS developer account creation is invalid / unreachable.

https://github.com/yandex/rtv/blob/41cb956527b7a62d3edd0068cd2cd1182c63f0cb/README.md?plain=1#L47

I suppose, it can be replaced with LG guide link.

https://webostv.developer.lge.com/develop/app-test/preparing-account/

If it's ok, I can create a PR fixing this issue.

**Comment by pfilatov92** [comment]
Hi!

Thank you for this issue! The link seems to be outdated. Your PR is welcome :)

**Comment by mikegsrv** [comment]
Sorry for the delay, created #13 to close this one.
