### ISSUE TITLE
Add new versions of DevTools

### ISSUE THREAD

**Issue by stamoern** [yandex/rtv#5]
Currently the latest versions of DevTools are devtools for tizen 4 (chromium56.0.2924.122) and webos 4 (54.0.2792.0)
https://github.com/yandex/rtv/tree/main/packages/server/public/devtools
I think it's time to add newer versions of devtools for newer versions of tizen and webos.

Perhaps it also makes sense to add ability to use TV devtools, not hosted on rtv-server

**Comment by pfilatov92** [comment]
Accepted 👍 Thnx for it!

**Comment by pfilatov92** [comment]
Fix is in [PR](https://github.com/yandex/rtv/pull/10)
